(function(){"use strict";var d=window.CPU,v=/^[ \t]*!?!\[[^\]\n]*\]\(\S+\)[ \t]*$/gm;function m(t){return'<div class="picker" style="margin-top:var(--space-2)" role="group" aria-label="Format the writing"><button type="button" class="btn btn--ghost btn--sm" data-md="h2" data-md-for="'+t+'">Heading</button><button type="button" class="btn btn--ghost btn--sm" data-md="h3" data-md-for="'+t+'">Sub heading</button><button type="button" class="btn btn--ghost btn--sm" data-md="bold" data-md-for="'+t+'">Bold</button><button type="button" class="btn btn--ghost btn--sm" data-md="table" data-md-for="'+t+'">Table</button></div><p class="cp-note">Heading and Sub heading turn the line the cursor is on into one. A table can be pasted straight from a document or a spreadsheet, or started with Table.</p><div class="picker" style="margin-top:var(--space-2)"><input class="input" data-photo-cap="'+t+'" autocomplete="off" aria-label="Caption for the photo or graphic" placeholder="Caption: who or what is in it" style="flex:1 1 220px"><label class="btn btn--ghost btn--sm" style="cursor:pointer;flex:0 0 auto">Add a photo<input type="file" accept="image/*" hidden data-photo-for="'+t+'"></label><label class="btn btn--ghost btn--sm" style="cursor:pointer;flex:0 0 auto">Add a graphic<input type="file" accept="image/*" hidden data-photo-for="'+t+'" data-graphic></label></div><p class="cp-note" data-photo-note="'+t+'">Type the caption first, then pick the picture. A photo fills the column; a graphic, such as a results card or a poster, is shown whole. It goes in where the cursor is, as its own line: move that line to move it, delete it to take it out.</p>'}function w(t,a){return new Promise(function(e){var n=URL.createObjectURL(t),o=new Image;o.onload=function(){var r=Math.min(1,a/o.width);URL.revokeObjectURL(n),e({width:Math.round(o.width*r),height:Math.round(o.height*r)})},o.onerror=function(){URL.revokeObjectURL(n),e({})},o.src=n})}function p(t,a,e){var n=String(t||"").replace(/[\[\]\r\n]+/g," ").replace(/\s+/g," ").trim(),o=a.width&&a.height?"#"+a.width+"x"+a.height:"";return(e?"!!":"!")+"["+n+"]("+a.url+o+")"}function y(t){return String(t||"").replace(v," ").replace(/^#+\s*/gm,"").replace(/[|*]/g," ").trim().split(/\s+/).filter(Boolean).length}function g(t){typeof Event=="function"&&t.dispatchEvent(new Event("input",{bubbles:!0}))}function h(t,a,e,n){var o=t.value.slice(0,a).replace(/\s+$/,""),r=t.value.slice(e).replace(/^\s+/,"");t.value=(o?o+`

`:"")+n+(r?`

`+r:"");var i=(o?o.length+2:0)+n.length;t.setSelectionRange&&t.setSelectionRange(i,i),g(t)}function f(t,a){var e=t.value,n=typeof t.selectionStart=="number"?t.selectionStart:e.length,o=typeof t.selectionEnd=="number"?t.selectionEnd:n;if(a==="bold"){var r=e.slice(n,o)||"bold words";t.value=e.slice(0,n)+"**"+r+"**"+e.slice(o),t.setSelectionRange&&t.setSelectionRange(n+2,n+2+r.length),g(t);return}if(a==="table"){h(t,n,o,`| Heading | Heading |
|---|---|
| Row | Value |
| Row | Value |`);return}var i=e.lastIndexOf(`
`,n-1)+1,l=e.indexOf(`
`,n);l<0&&(l=e.length);var s=e.slice(i,l).replace(/^#+\s*/,"").trim()||(a==="h2"?"Heading":"Sub heading");h(t,i,l,(a==="h2"?"## ":"### ")+s)}function S(t){t.addEventListener("click",function(a){var e=a.target&&a.target.closest&&a.target.closest("[data-md]");if(e){var n=t.querySelector("#"+e.getAttribute("data-md-for"));n&&(f(n,e.getAttribute("data-md")),n.focus())}}),t.addEventListener("change",function(a){var e=a.target&&a.target.closest&&a.target.closest("[data-photo-for]");if(e){var n=e.files&&e.files[0];if(n){if(!d.guard()){e.value="";return}var o=e.getAttribute("data-photo-for"),r=e.hasAttribute("data-graphic"),i=t.querySelector("#"+o),l=t.querySelector('[data-photo-cap="'+o+'"]'),s=t.querySelector('[data-photo-note="'+o+'"]');if(i){var b=typeof i.selectionStart=="number"?i.selectionStart:i.value.length;s&&(s.textContent="Uploading."),Promise.all([d.uploadImage(n,{max:1600,prefix:r?"graphic":"photo",keepAlpha:r}),w(n,1600)]).then(function(c){var u=c[0];u.width=c[1].width,u.height=c[1].height,h(i,b,b,p(l&&l.value,u,r)),l&&(l.value=""),e.value="",s&&(s.textContent="Added, "+Math.round(u.was/1024)+" KB down to "+Math.round(u.now/1024)+" KB. Save to keep it.")}).catch(function(c){s&&(s.textContent=c.message),e.value=""})}}}})}window.CPWRITE={photoField:m,photoLine:p,proseWords:y,wirePhotos:S,format:f}})();
